[package]
edition = "2024"
rust-version = "1.89"
name = "stardust-xr-wayland-service"
version = "0.50.0"
authors = ["Nova King <technobaboo@proton.me>"]
description = "Wayland Compatibillity service for Stardust XR"
license = "GPLv2"
# repository = "https://github.com/StardustXR/stardust-xr-server/"
homepage = "https://stardustxr.org"

[workspace]
members = ["display-socket-finder"]

[workspace.dependencies]
mint = "0.5.9"
stardust-xr-gluon = { git = "https://github.com/StardustXR/core.git", version = "0.50.0" }
stardust-xr-fusion = { git = "https://github.com/StardustXR/core.git", version = "0.50.0" }
stardust-xr-wire = { git = "https://github.com/StardustXR/core.git", version = "0.50.0" }
stardust-xr-cme = { git = "https://github.com/StardustXR/cme.git", version = "0.50.0" }
stardust-xr-molecules = { git = "https://github.com/StardustXR/molecules.git", version = "0.50.0" }
vulkano = { git = "https://github.com/Schmarni-Dev/vulkano", branch = "0_35_dmabuf_fixes", default-features = false }

[dependencies]
waynest = { git = "https://github.com/verdiwm/waynest.git", default-features = false }
waynest-protocols = { git = "https://github.com/verdiwm/waynest.git", features = [
	"server",
	"stable",
	"unstable",
	"mesa",
	"tracing",
], default-features = false }
waynest-server = { git = "https://github.com/verdiwm/waynest.git", default-features = false }
tokio-stream = "0.1.17"
memmap2 = "0.9.5"
drm-fourcc = "2.2.0"
memfd = "0.6.4"
rustix = { version = "1.1.3", features = ["time"] }
pin-project-lite = "0.2.16"
futures-sink = "0.3.31"
tokio = { version = "1.49.0", features = [
	"macros",
	"rt",
	"rt-multi-thread",
	"tracing",
] }
tracing = { version = "0.1.44", features = ["async-await"] }
tracing-subscriber = "0.3.22"
thiserror = "2.0.17"
directories = "6.0.0"
dashmap = "6.1.0"
slotmap = "1.1.1"
input-event-codes = "6.2.0"
parking_lot = "0.12.5"
mint.workspace = true
# stardust-xr-gluon.workspace = true
stardust-xr-fusion.workspace = true
stardust-xr-cme.workspace = true
vulkano.workspace = true
