appid := env('APPID')
install-dir := env('INSTALL_DIR')
res-src := appid
res-dst := install-dir / appid

install:
    mkdir -p {{ res-dst }}
    install -Dm0644 {{ res-src }}/* {{ res-dst }}

uninstall:
    rm -r {{ res-dst }}
